/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import recognition.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.UIManager;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author samar
 */
public class add_student extends javax.swing.JPanel {

    /**
     * Creates new form attendance_fill_manually
     */
    public add_student() {
        initComponents(); 
    }
     Connection Con = null;
    Statement St = null;
    ResultSet Rs=null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stud_gender = new javax.swing.ButtonGroup();
        jButton_save = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Stud_name = new javax.swing.JTextField();
        Stud_mob = new javax.swing.JTextField();
        Roll_no = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton_browse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Stud_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Stud_img = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCombo_Stud_dept = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jCombo_Stud_div = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jCombo_Stud_year = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Stud_email = new javax.swing.JTextField();
        dayCombo = new javax.swing.JComboBox();
        monthCombo = new javax.swing.JComboBox();
        yearCombo = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(740, 520));
        setMinimumSize(new java.awt.Dimension(740, 520));
        setPreferredSize(new java.awt.Dimension(740, 520));

        jButton_save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(51, 51, 51));
        jButton_save.setText("SAVE");
        jButton_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_saveMouseClicked(evt);
            }
        });
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jButton_clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_clear.setForeground(new java.awt.Color(51, 51, 51));
        jButton_clear.setText("RESET");
        jButton_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_clearMouseClicked(evt);
            }
        });
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 255, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("*Default Username & Password: (Student ID)");
        jLabel9.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        Stud_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Stud_name.setForeground(new java.awt.Color(51, 51, 51));
        Stud_name.setAutoscrolls(false);
        Stud_name.setMinimumSize(new java.awt.Dimension(6, 30));

        Stud_mob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Stud_mob.setForeground(new java.awt.Color(51, 51, 51));
        Stud_mob.setAutoscrolls(false);
        Stud_mob.setMinimumSize(new java.awt.Dimension(6, 30));

        Roll_no.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Roll_no.setForeground(new java.awt.Color(51, 51, 51));
        Roll_no.setAutoscrolls(false);
        Roll_no.setMinimumSize(new java.awt.Dimension(6, 30));
        Roll_no.setPreferredSize(new java.awt.Dimension(72, 25));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("UPLOAD IMAGE :");

        jButton_browse.setBackground(new java.awt.Color(255, 255, 255));
        jButton_browse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_browse.setForeground(new java.awt.Color(51, 51, 51));
        jButton_browse.setText("..BROWSE");
        jButton_browse.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton_browse.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton_browse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_browseMouseClicked(evt);
            }
        });
        jButton_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("DEPARTMENT :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("DOB :");

        Stud_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Stud_id.setForeground(new java.awt.Color(51, 51, 51));
        Stud_id.setAutoscrolls(false);
        Stud_id.setMinimumSize(new java.awt.Dimension(6, 30));
        Stud_id.setPreferredSize(new java.awt.Dimension(72, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("ROLL NO :");
        jLabel10.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("STUDENT NAME :");

        Stud_gender.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton2.setText("FEMALE");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("CLASS :");

        Stud_img.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Stud_img.setForeground(new java.awt.Color(51, 51, 51));
        Stud_img.setAutoscrolls(false);
        Stud_img.setMinimumSize(new java.awt.Dimension(6, 25));
        Stud_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stud_imgActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("EMAIL ID:");

        jCombo_Stud_dept.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCombo_Stud_dept.setForeground(new java.awt.Color(51, 51, 51));
        jCombo_Stud_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Mechanical (ME)", "Information Technology(IT)", "Chemical(CE)" }));
        jCombo_Stud_dept.setMinimumSize(new java.awt.Dimension(6, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("MOBILE NO :");

        jCombo_Stud_div.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCombo_Stud_div.setForeground(new java.awt.Color(51, 51, 51));
        jCombo_Stud_div.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jCombo_Stud_div.setMinimumSize(new java.awt.Dimension(6, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("GENDER :");

        Stud_gender.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton1.setText("MALE");

        jCombo_Stud_year.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCombo_Stud_year.setForeground(new java.awt.Color(51, 51, 51));
        jCombo_Stud_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Year", "Second Year", "Third Year", "Fourth Year" }));
        jCombo_Stud_year.setMinimumSize(new java.awt.Dimension(6, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("STUDENT ID :");
        jLabel1.setToolTipText("");

        Stud_email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Stud_email.setForeground(new java.awt.Color(51, 51, 51));
        Stud_email.setAutoscrolls(false);
        Stud_email.setMinimumSize(new java.awt.Dimension(6, 30));

        dayCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dayCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayCombo.setToolTipText("Day");
        dayCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayComboActionPerformed(evt);
            }
        });

        monthCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monthCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        monthCombo.setToolTipText("Month");

        yearCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yearCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        yearCombo.setToolTipText("Year");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Stud_id, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Roll_no, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Stud_name, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(70, 70, 70)
                        .addComponent(Stud_email, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(Stud_mob, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jCombo_Stud_year, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jCombo_Stud_div, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jCombo_Stud_dept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(Stud_img, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_browse))))
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(74, 74, 74)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Roll_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Stud_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stud_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stud_email, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stud_mob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo_Stud_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo_Stud_year, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo_Stud_div, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stud_img, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jButton_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Stud_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stud_imgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Stud_imgActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_saveMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jButton_saveMouseClicked

    private void dayComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayComboActionPerformed

    private void jButton_browseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_browseMouseClicked
        // TODO add your handling code here:
        
        //JFileChooser chooser = new JFileChooser();
    }//GEN-LAST:event_jButton_browseMouseClicked

    private void jButton_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_clearMouseClicked
        // TODO add your handling code here:
        Stud_id.setText("");
        Roll_no.setText("");
        Stud_name.setText("");
        dayCombo.setSelectedIndex(0);
        monthCombo.setSelectedIndex(0);
        yearCombo.setSelectedIndex(0);
        Stud_gender.clearSelection();
        Stud_email.setText("");
        Stud_mob.setText("");
        jCombo_Stud_dept.setSelectedIndex(0);
        jCombo_Stud_year.setSelectedIndex(0);
        jCombo_Stud_div.setSelectedIndex(0);
        Stud_img.setText("");
    }//GEN-LAST:event_jButton_clearMouseClicked

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
         if(Stud_id.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else
        {
            try
            {
               Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
               Con = DriverManager.getConnection("jdbc:ucanaccess://attendance_db/face_recog_db.accdb");
               PreparedStatement add = Con.prepareStatement("insert into student(stud_id,stud_roll,stud_name,stud_dob,stud_gender,stud_email,stud_mobile,stud_dept,stud_year,stud_div,stud_dataset,stud_uname,stud_pwd) values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
                
                String d = dayCombo.getSelectedItem().toString();
                String m = monthCombo.getSelectedItem().toString();
                String y = yearCombo.getSelectedItem().toString();
                String dob = d + "-" + m + "-" + y;
                
                String gen;
                if(jRadioButton1.isSelected()){
                    gen = jRadioButton1.getText();
                }
                else {
                    gen = jRadioButton2.getText();
                }
                
                add.setInt(1, Integer.valueOf(Stud_id.getText()));
                add.setInt(2, Integer.valueOf(Roll_no.getText()));
                add.setString(3, Stud_name.getText());
                add.setString(4, dob);
                add.setString(5, gen);
                add.setString(6, Stud_email.getText());
                add.setString(7, Stud_mob.getText());
                add.setString(8, jCombo_Stud_dept.getSelectedItem().toString());
                add.setString(9, jCombo_Stud_year.getSelectedItem().toString());
                add.setString(10, jCombo_Stud_div.getSelectedItem().toString());
                add.setString(11, Stud_img.getText());
                add.setString(12, Stud_email.getText());
                add.setString(13, Stud_id.getText());
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, " Student Record Added Succesfully..! ");
                Con.close();
                
                FaceDetector fd = new FaceDetector();
                fd.init("Face_recog_Project_attendance/stud_images/"+ Stud_id.getText(), Integer.parseInt(Stud_id.getText()),Stud_name.getText());
                    
            }catch(Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browseActionPerformed
        
        
        if(!Stud_id.getText().isEmpty())
        {
            try
            {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
             
            JFileChooser file = new JFileChooser();
            file.setMultiSelectionEnabled(true);
            file.setFileSelectionMode(JFileChooser.FILES_ONLY);
            file.setFileHidingEnabled(false);


            if (file.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                File[] f = file.getSelectedFiles();

                if(f != null)
                {


                    System.err.println("Accepted file received");            
                    File theDir = new File("Face_recog_Project_attendance/stud_images/"+ Stud_id.getText());
                    if (!theDir.exists()){
                        theDir.mkdirs();
                    }

                    int i=0;
                    for (File t: f)
                    {
                        System.err.println("File" + i + ": " + t.getPath()); i++;

                        File source = new File(t.getPath());
                        File dest = new File("Face_recog_Project_attendance/stud_images/" + Stud_id.getText() + "/" + i + ".jpg");
                        try {
                            //FileUtils.copyFile(source, dest);
                            Files.copy(source.toPath(), dest.toPath(), StandardCopyOption.REPLACE_EXISTING);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }                
                }
              }
     
        
       
            Stud_img.setText("Face_recog_Project_attendance/stud_images/" + Stud_id.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Provide Student Id Firstly :)");
        }
    }//GEN-LAST:event_jButton_browseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Roll_no;
    private javax.swing.JTextField Stud_email;
    private javax.swing.ButtonGroup Stud_gender;
    private javax.swing.JTextField Stud_id;
    private javax.swing.JTextField Stud_img;
    private javax.swing.JTextField Stud_mob;
    private javax.swing.JTextField Stud_name;
    private javax.swing.JComboBox dayCombo;
    private javax.swing.JButton jButton_browse;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_save;
    private javax.swing.JComboBox<String> jCombo_Stud_dept;
    private javax.swing.JComboBox<String> jCombo_Stud_div;
    private javax.swing.JComboBox<String> jCombo_Stud_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JComboBox monthCombo;
    private javax.swing.JComboBox yearCombo;
    // End of variables declaration//GEN-END:variables

}




