/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.CardLayout;

/**
 *
 * @author samar
 */
public class attendance extends javax.swing.JPanel {

    /**
     * Creates new form attendance
     */
    public attendance() {
        initComponents();
        
//        subject sub = new subject();
//        faculty fac = new faculty();
//        attendance attend = new attendance();
//        student stud = new student();
//        attendance_fill_manually manually = new attendance_fill_manually();
        view_attendance view_attend = new view_attendance();
//        modify_attendance edit_attend = new modify_attendance();
        mark_attendance mark_attend = new mark_attendance();
        
        sub_tab_holder_attendance.setLayout(new CardLayout());
        
        sub_tab_holder_attendance.add("mark attendance", mark_attend);
//        sub_tab_holder_attendance.add("manually", manually);
        sub_tab_holder_attendance.add("view attendance", view_attend);
//         sub_tab_holder_attendance.add("edit attendance", edit_attend);
         
//        tab_holder.add("faculty", fac);
//        tab_holder.add("attendance", attend);
//        tab_holder.add("student",stud);  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sub_tab_holder_attendance = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        label_allot_subject = new javax.swing.JLabel();
        label_view_subject = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(940, 540));
        setMinimumSize(new java.awt.Dimension(940, 540));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(940, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub_tab_holder_attendance.setBackground(new java.awt.Color(255, 255, 255));
        sub_tab_holder_attendance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 51), 2));
        sub_tab_holder_attendance.setMaximumSize(new java.awt.Dimension(680, 520));
        sub_tab_holder_attendance.setMinimumSize(new java.awt.Dimension(680, 520));
        sub_tab_holder_attendance.setRequestFocusEnabled(false);

        javax.swing.GroupLayout sub_tab_holder_attendanceLayout = new javax.swing.GroupLayout(sub_tab_holder_attendance);
        sub_tab_holder_attendance.setLayout(sub_tab_holder_attendanceLayout);
        sub_tab_holder_attendanceLayout.setHorizontalGroup(
            sub_tab_holder_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        sub_tab_holder_attendanceLayout.setVerticalGroup(
            sub_tab_holder_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        add(sub_tab_holder_attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 740, -1));
        sub_tab_holder_attendance.getAccessibleContext().setAccessibleDescription("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(204, 255, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_allot_subject.setBackground(new java.awt.Color(204, 255, 51));
        label_allot_subject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_allot_subject.setForeground(new java.awt.Color(51, 51, 51));
        label_allot_subject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_allot_subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/allot_32.png"))); // NOI18N
        label_allot_subject.setText("MARK ATTENDANCE");
        label_allot_subject.setName("label_allot_subject"); // NOI18N
        label_allot_subject.setOpaque(true);
        label_allot_subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_allot_subjectMouseClicked(evt);
            }
        });

        label_view_subject.setBackground(new java.awt.Color(204, 255, 51));
        label_view_subject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_view_subject.setForeground(new java.awt.Color(51, 51, 51));
        label_view_subject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_view_subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/view_32.png"))); // NOI18N
        label_view_subject.setText("VIEW ATTENDANCE");
        label_view_subject.setName("label_view_subject"); // NOI18N
        label_view_subject.setOpaque(true);
        label_view_subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_view_subjectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_allot_subject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_view_subject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(label_allot_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_view_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 180, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void label_allot_subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_allot_subjectMouseClicked
        CardLayout cl = (CardLayout) sub_tab_holder_attendance.getLayout();
        cl.show(sub_tab_holder_attendance, "mark attendance");
    }//GEN-LAST:event_label_allot_subjectMouseClicked

    private void label_view_subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_view_subjectMouseClicked
        CardLayout cl = (CardLayout) sub_tab_holder_attendance.getLayout();
        cl.show(sub_tab_holder_attendance, "view attendance");
    }//GEN-LAST:event_label_view_subjectMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel label_allot_subject;
    private javax.swing.JLabel label_view_subject;
    private javax.swing.JPanel sub_tab_holder_attendance;
    // End of variables declaration//GEN-END:variables
}
