/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.CardLayout;
import java.awt.Label;
//import javafx.scene.paint.Color;
import javax.swing.JPanel;

/**
 *
 * @author SAMARTH MISAL
 */



public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        
        
        subject sub = new subject();
        faculty fac = new faculty();
        attendance attend = new attendance();
        student stud = new student();
        
        tab_holder.setLayout(new CardLayout());

        tab_holder.add("faculty", fac);
        tab_holder.add("subject", sub);
        tab_holder.add("attendance", attend);
        tab_holder.add("student",stud);     
        label_faculty.setBackground(java.awt.Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab_holder = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_faculty = new javax.swing.JLabel();
        label_student = new javax.swing.JLabel();
        label_subject = new javax.swing.JLabel();
        label_attendance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(940, 700));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(880, 700));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel1.setMaximumSize(new java.awt.Dimension(940, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(940, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_holder.setBackground(new java.awt.Color(255, 255, 255));
        tab_holder.setMaximumSize(new java.awt.Dimension(940, 540));
        tab_holder.setMinimumSize(new java.awt.Dimension(940, 540));
        tab_holder.setName(""); // NOI18N
        tab_holder.setPreferredSize(new java.awt.Dimension(940, 540));
        tab_holder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        tab_holder.setLayout(null);
        jPanel1.add(tab_holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));
        tab_holder.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(204, 255, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(940, 160));
        jPanel2.setMinimumSize(new java.awt.Dimension(940, 160));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(940, 160));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_MacOS_Close_30px.png"))); // NOI18N
        exit.setToolTipText("Close");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_facial_recognition_scan_26px_2.png"))); // NOI18N
        jLabel1.setText("  Face Recognition Attendance System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 30));

        label_faculty.setBackground(new java.awt.Color(204, 255, 51));
        label_faculty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_faculty.setForeground(new java.awt.Color(51, 51, 51));
        label_faculty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_faculty.setText("FACULTY");
        label_faculty.setName("label_faculty"); // NOI18N
        label_faculty.setOpaque(true);
        label_faculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_facultyMouseClicked(evt);
            }
        });
        jPanel2.add(label_faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 40));

        label_student.setBackground(new java.awt.Color(204, 255, 51));
        label_student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_student.setForeground(new java.awt.Color(51, 51, 51));
        label_student.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_student.setText("STUDENT");
        label_student.setName("label_student"); // NOI18N
        label_student.setOpaque(true);
        label_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_studentMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_studentMouseReleased(evt);
            }
        });
        jPanel2.add(label_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, 40));

        label_subject.setBackground(new java.awt.Color(204, 255, 51));
        label_subject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_subject.setForeground(new java.awt.Color(51, 51, 51));
        label_subject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_subject.setText("SUBJECT");
        label_subject.setName("label_faculty"); // NOI18N
        label_subject.setOpaque(true);
        label_subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_subjectMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_subjectMouseReleased(evt);
            }
        });
        jPanel2.add(label_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 110, 40));

        label_attendance.setBackground(new java.awt.Color(204, 255, 51));
        label_attendance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_attendance.setForeground(new java.awt.Color(51, 51, 51));
        label_attendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_attendance.setText("ATTENDANCE");
        label_attendance.setName("label_faculty"); // NOI18N
        label_attendance.setOpaque(true);
        label_attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_attendanceMouseClicked(evt);
            }
        });
        jPanel2.add(label_attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        this.setLocation(getLocation());

    }//GEN-LAST:event_jPanel2MouseDragged

    private void label_attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_attendanceMouseClicked
        // TODO add your handling code here:

        CardLayout cl = (CardLayout) tab_holder.getLayout();
        cl.show(tab_holder, "attendance");

        label_faculty.setBackground(new java.awt.Color(204,255,51));
        label_student.setBackground(new java.awt.Color(204,255,51));
        label_subject.setBackground(new java.awt.Color(204,255,51));
        label_attendance.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_label_attendanceMouseClicked

    private void label_subjectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_subjectMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_label_subjectMouseReleased

    private void label_subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_subjectMouseClicked
        // TODO add your handling code here:

        CardLayout cl = (CardLayout) tab_holder.getLayout();
        cl.show(tab_holder, "subject");

        label_subject.setBackground(java.awt.Color.white);

        label_faculty.setBackground(new java.awt.Color(204,255,51));
        label_student.setBackground(new java.awt.Color(204,255,51));
        label_attendance.setBackground(new java.awt.Color(204,255,51));
    }//GEN-LAST:event_label_subjectMouseClicked

    private void label_studentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_studentMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_studentMouseReleased

    private void label_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_studentMouseClicked
        // TODO add your handling code here:

        CardLayout cl = (CardLayout) tab_holder.getLayout();
        cl.show(tab_holder, "student");

        label_faculty.setBackground(new java.awt.Color(204,255,51));
        label_subject.setBackground(new java.awt.Color(204,255,51));
        label_attendance.setBackground(new java.awt.Color(204,255,51));
        label_student.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_label_studentMouseClicked

    private void label_facultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_facultyMouseClicked
        // TODO add your handling code here:

        CardLayout cl = (CardLayout) tab_holder.getLayout();
        cl.show(tab_holder, "faculty");

        label_faculty.setBackground(java.awt.Color.white);
        label_student.setBackground(new java.awt.Color(204,255,51));
        label_subject.setBackground(new java.awt.Color(204,255,51));
        label_attendance.setBackground(new java.awt.Color(204,255,51));

    }//GEN-LAST:event_label_facultyMouseClicked

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
    }//GEN-LAST:event_formMouseDragged
    
    void reset_tab_colors()
    {
        label_faculty.setBackground(new java.awt.Color(204,255,51));
        label_student.setBackground(new java.awt.Color(204,255,51));
        label_subject.setBackground(new java.awt.Color(204,255,51));
        label_attendance.setBackground(new java.awt.Color(204,255,51));
    }
    
    int xx,xy; public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(197, 197, 197));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(240,240,240));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_attendance;
    private javax.swing.JLabel label_faculty;
    private javax.swing.JLabel label_student;
    private javax.swing.JLabel label_subject;
    private javax.swing.JPanel tab_holder;
    // End of variables declaration//GEN-END:variables
}
