/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.File;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.SortedSet;
import javax.swing.JOptionPane;
import org.bytedeco.javacpp.opencv_face;
import recognition.FaceRecognizer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import org.bytedeco.javacpp.opencv_core;


/**
 *
 * @author samar
 */
public class mark_attendance extends javax.swing.JPanel {

    static int img_cnt=0;
     
    Connection Con = null;
    Statement St = null;
    ResultSet Rs=null;
    SortedSet<Integer> face_codes;
    /**
     * Creates new form attendance_fill_manually
     */
    public mark_attendance() {
        initComponents();
        clear_temp();
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_attend = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        div = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sub = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        dept = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        d2 = new javax.swing.JComboBox();
        d3 = new javax.swing.JComboBox();
        d1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        Stud_img = new javax.swing.JTextField();
        jButton_browse = new javax.swing.JButton();
        detect_faces = new javax.swing.JButton();
        mark_attendance = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(740, 520));
        setMinimumSize(new java.awt.Dimension(740, 520));
        setPreferredSize(new java.awt.Dimension(740, 520));

        table_attend.setAutoCreateRowSorter(true);
        table_attend.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        table_attend.setForeground(new java.awt.Color(51, 51, 51));
        table_attend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_attend.setColumnSelectionAllowed(true);
        table_attend.setMinimumSize(new java.awt.Dimension(404, 440));
        table_attend.setPreferredSize(new java.awt.Dimension(404, 440));
        jScrollPane1.setViewportView(table_attend);
        table_attend.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("DATE :");

        div.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        div.setForeground(new java.awt.Color(51, 51, 51));
        div.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        div.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("SUBJECT :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("YEAR :");

        sub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sub.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("DEPARTMENT :");
        jLabel1.setToolTipText("");

        dept.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dept.setForeground(new java.awt.Color(51, 51, 51));
        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Mechanical (ME)", "Information Technology(IT)", "Chemical(CE)" }));
        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });

        year.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        year.setForeground(new java.awt.Color(51, 51, 51));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Year", "Second Year", "Third Year", "Fourth Year" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("DIV :");

        d2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d2.setForeground(new java.awt.Color(51, 51, 51));
        d2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        d2.setToolTipText("Month");
        d2.setMinimumSize(new java.awt.Dimension(71, 21));
        d2.setPreferredSize(new java.awt.Dimension(71, 21));

        d3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d3.setForeground(new java.awt.Color(51, 51, 51));
        d3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        d3.setToolTipText("Year");
        d3.setMinimumSize(new java.awt.Dimension(71, 21));
        d3.setPreferredSize(new java.awt.Dimension(71, 21));

        d1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d1.setForeground(new java.awt.Color(51, 51, 51));
        d1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        d1.setToolTipText("Day");
        d1.setMinimumSize(new java.awt.Dimension(71, 21));
        d1.setPreferredSize(new java.awt.Dimension(71, 21));
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("UPLOAD IMAGES");

        Stud_img.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Stud_img.setForeground(new java.awt.Color(51, 51, 51));
        Stud_img.setAutoscrolls(false);
        Stud_img.setMinimumSize(new java.awt.Dimension(6, 25));
        Stud_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stud_imgActionPerformed(evt);
            }
        });

        jButton_browse.setBackground(new java.awt.Color(255, 255, 255));
        jButton_browse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_browse.setForeground(new java.awt.Color(51, 51, 51));
        jButton_browse.setText("..BROWSE");
        jButton_browse.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton_browse.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton_browse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_browseMouseClicked(evt);
            }
        });
        jButton_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browseActionPerformed(evt);
            }
        });

        detect_faces.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        detect_faces.setForeground(new java.awt.Color(51, 51, 51));
        detect_faces.setText("Detect Faces");
        detect_faces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detect_facesActionPerformed(evt);
            }
        });

        mark_attendance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mark_attendance.setForeground(new java.awt.Color(51, 51, 51));
        mark_attendance.setText("Mark Attendance");
        mark_attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark_attendanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(Stud_img, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(detect_faces, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mark_attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton_browse, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Stud_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detect_faces, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mark_attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void Stud_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stud_imgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Stud_imgActionPerformed

    private void jButton_browseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_browseMouseClicked
        // TODO add your handling code here:

        //JFileChooser chooser = new JFileChooser();
    }//GEN-LAST:event_jButton_browseMouseClicked

    private void jButton_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browseActionPerformed

        if(true)
        {

            JFileChooser file = new JFileChooser();
            file.setMultiSelectionEnabled(true);
            file.setFileSelectionMode(JFileChooser.FILES_ONLY);
            file.setFileHidingEnabled(false);

            if (file.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) 
            {
                File[] f = file.getSelectedFiles();
                
                if(f != null)
                {

                    System.err.println("Accepted file received");
                    File theDir = new File("Face_recog_Project_attendance/stud_temp");
                    if (!theDir.exists()){
                        theDir.mkdirs();
                    }
                    
                    for (File t: f)
                    {
                        System.err.println("File" +  img_cnt + ": " + t.getPath()); img_cnt++;

                        File source = new File(t.getPath());
                        File dest = new File("Face_recog_Project_attendance/stud_temp/"  + img_cnt + ".jpg");
                        try {
                            //FileUtils.copyFile(source, dest);
                            Files.copy(source.toPath(), dest.toPath(), StandardCopyOption.REPLACE_EXISTING);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                   }
                }
            }

                Stud_img.setText("Face_recog_Project_attendance/stud_images/");
        }
    }//GEN-LAST:event_jButton_browseActionPerformed

    private void detect_facesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detect_facesActionPerformed
        
        if(sub.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this,"Kindly Select A Subject !");    
            return;
        }
        

        FaceRecognizer f = new FaceRecognizer();
        face_codes = f.call_me();
        System.err.println(face_codes);        
        
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Con = DriverManager.getConnection("jdbc:ucanaccess://attendance_db/face_recog_db.accdb");
            Statement St = null;
            ResultSet Rs=null;
            St = Con.createStatement();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Roll No ");
            model.addColumn("Student Name");
            
            for(int code: face_codes)
            {
                Rs = St.executeQuery("Select * from student where stud_id='"+ code +"'");
                if(Rs.next())
                {
                    String[] temp_row = {   Rs.getString("stud_id"),
                                        Rs.getString("stud_roll"),
                                        Rs.getString("stud_name") 
                                    };
                    model.addRow(temp_row);
                }
            }
            
            table_attend.setModel(model);
            
            Con.close();
            
        } catch (Exception e) {
            System.err.println(e);
        }    
        
    }//GEN-LAST:event_detect_facesActionPerformed

    
    
    private void mark_attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark_attendanceActionPerformed
        clear_temp();
        
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Con = DriverManager.getConnection("jdbc:ucanaccess://attendance_db/face_recog_db.accdb");
            
            
            String d = d1.getSelectedItem().toString();
            String m = d2.getSelectedItem().toString();
            String y = d3.getSelectedItem().toString();
            String date = d + "-" + m + "-" + y;
            int sub_id = 0;
            
            St = Con.createStatement();
        
            Rs = St.executeQuery("Select sub_code from subject where sub_name='"+ sub.getSelectedItem().toString()+"'");
        
            if(Rs.next())
            {
                sub_id = Rs.getInt("sub_code");
            }
            System.err.println(sub_id);
            PreparedStatement add = Con.prepareStatement("insert into attendance_subject(subject_id,date_attend,department,year,div,stud_id) values(?,?,?,?,?,?)");
            
            add.setInt(1, sub_id);//Integer.valueOf(sub_id));
            add.setString(2, date);
            add.setString(3, dept.getSelectedItem().toString());
            add.setString(4, year.getSelectedItem().toString());
            add.setString(5, div.getSelectedItem().toString());
            
            for(int code: face_codes)
            {
                System.err.println("For Code: "  + code);
                add.setInt(6,code  );
                int row = add.executeUpdate();
            }
            
            JOptionPane.showMessageDialog(this, " Attendance Marked Successfully..! ");
            
            Con.close();
            
        } catch (Exception e) {
            System.err.println(e);
        }    
    }//GEN-LAST:event_mark_attendanceActionPerformed

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptActionPerformed
        sub.removeAllItems();
        try
        {
         Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
         Con = DriverManager.getConnection("jdbc:ucanaccess://attendance_db/face_recog_db.accdb");
         St = Con.createStatement();
        // String Query="Select * from subject";
         Rs = St.executeQuery("Select * from subject where sub_course='"+ dept.getSelectedItem().toString()+"'");
        // Rs = St.executeQuery(Query);
         while(Rs.next())
         {
             String Mycat=Rs.getString("sub_name");
            sub.addItem(Mycat);
          
         }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deptActionPerformed

    public void clear_temp()
    {
    File theDir = new File("Face_recog_Project_attendance/stud_temp");
        if (!theDir.exists()){
            theDir.mkdirs();
        }

        for (File fi: theDir.listFiles()) {
            if (!fi.isDirectory())
                fi.delete();
        }
        System.err.println("Temp Directory Cleared ");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Stud_img;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox d1;
    private javax.swing.JComboBox d2;
    private javax.swing.JComboBox d3;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JButton detect_faces;
    private javax.swing.JComboBox<String> div;
    private javax.swing.JButton jButton_browse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mark_attendance;
    private javax.swing.JComboBox<String> sub;
    private javax.swing.JTable table_attend;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables

}




