/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author samar
 */
public class modify_subject extends javax.swing.JPanel {

    /**
     * Creates new form attendance_fill_manually
     */
    public modify_subject() {
        initComponents();
       GetCat();
       // GetCourse();
        
           
        
    }
    Connection Con = null;
    Statement St = null;
    ResultSet Rs=null;
     public void GetCat()
     {
        
     }
     /* private void GetCourse()
     {
          try
        {
         Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
         Con = DriverManager.getConnection("jdbc:ucanaccess://F:\\face_recog_db.accdb");
         St = Con.createStatement();
         String Query="Select * from subject";
         Rs = St.executeQuery(Query);
         while(Rs.next())
         {
             String Mycat=Rs.getString("sub_course");
             coursecb.addItem(Mycat);
         }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
     }*/


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox6 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        coursecb = new javax.swing.JComboBox<>();
        subname = new javax.swing.JTextField();
        subcode = new javax.swing.JTextField();
        thours = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        valCode = new javax.swing.JTextField();
        valName = new javax.swing.JTextField();
        valHours = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Code = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(740, 520));
        setMinimumSize(new java.awt.Dimension(740, 520));
        setPreferredSize(new java.awt.Dimension(740, 520));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)), " MODIFY DETAILS ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("COURSE");

        coursecb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        coursecb.setForeground(new java.awt.Color(51, 51, 51));
        coursecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Mechanical (ME)", "Information Technology(IT)", "Chemical(CE)" }));
        coursecb.setPreferredSize(new java.awt.Dimension(166, 25));

        subname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subname.setForeground(new java.awt.Color(51, 51, 51));
        subname.setAutoscrolls(false);
        subname.setMinimumSize(new java.awt.Dimension(6, 25));
        subname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                subnameKeyReleased(evt);
            }
        });

        subcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subcode.setForeground(new java.awt.Color(51, 51, 51));
        subcode.setAutoscrolls(false);
        subcode.setMinimumSize(new java.awt.Dimension(6, 25));
        subcode.setPreferredSize(new java.awt.Dimension(72, 25));
        subcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subcodeMouseEntered(evt);
            }
        });
        subcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                subcodeKeyReleased(evt);
            }
        });

        thours.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thours.setForeground(new java.awt.Color(51, 51, 51));
        thours.setAutoscrolls(false);
        thours.setMinimumSize(new java.awt.Dimension(6, 25));
        thours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                thoursKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("TEACHING HOURS :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("SUBJECT NAME :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("SUBJECT CODE :");
        jLabel1.setToolTipText("");

        valCode.setBackground(new java.awt.Color(240, 240, 240));
        valCode.setForeground(new java.awt.Color(255, 0, 0));
        valCode.setBorder(null);

        valName.setBackground(new java.awt.Color(240, 240, 240));
        valName.setForeground(new java.awt.Color(255, 0, 0));
        valName.setBorder(null);
        valName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valNameActionPerformed(evt);
            }
        });

        valHours.setBackground(new java.awt.Color(240, 240, 240));
        valHours.setForeground(new java.awt.Color(255, 0, 0));
        valHours.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valHours, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valCode, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subcode, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thours, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coursecb, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subname, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subcode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(valCode, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subname, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(valHours, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(valName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coursecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(51, 51, 51));
        update.setText("UPDATE DETAILS");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 255, 255));
        reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reset.setForeground(new java.awt.Color(51, 51, 51));
        reset.setText("RESET");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)), " SELECT SUBJECT ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        Code.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Code.setForeground(new java.awt.Color(51, 51, 51));
        Code.setPreferredSize(new java.awt.Dimension(166, 25));
        Code.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                CodeComponentAdded(evt);
            }
        });
        Code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CodeMouseEntered(evt);
            }
        });
        Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("SUBJECT CODE :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Code, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(update)
                        .addGap(26, 26, 26)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeActionPerformed
        // TODO add your handling code here:
        
           
        
       
    }//GEN-LAST:event_CodeActionPerformed

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        GetCat();  
        if(subcode.getText().isEmpty()||subname.getText().isEmpty()||thours.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Details missing");
        }
        else
        {
            try{
               Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
              Con = DriverManager.getConnection("jdbc:ucanaccess://attendance_db/face_recog_db.accdb");
               String Query ="Update subject set sub_name='"+subname.getText()+"'"+",sub_teachhours='"+thours.getText()+"'"+",sub_course='"+coursecb.getSelectedItem().toString()+"'"+"where sub_code="+subcode.getText();
                Statement Add= Con.createStatement();
                Add.executeUpdate(Query);
                JOptionPane.showMessageDialog(this, "Subject Updated");
                 
                
                    
                
            }catch(SQLException e)
            {
                e.printStackTrace();
            } catch (ClassNotFoundException ex) {
                 Logger.getLogger(modify_subject.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        
        
        
    }//GEN-LAST:event_updateMouseClicked

    private void CodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodeMouseEntered
        // TODO add your handling code here:
        Code.removeAllItems();
        try
        {
         Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
         Con = DriverManager.getConnection("jdbc:ucanaccess://attendance_db/face_recog_db.accdb");
         St = Con.createStatement();
         String Query="Select * from subject";
         Rs = St.executeQuery(Query);
         while(Rs.next())
         {
             String Mycat=Rs.getString("sub_code");
             Code.addItem(Mycat);
          
         }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        
        
        
        
    }//GEN-LAST:event_CodeMouseEntered

    private void CodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodeMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_CodeMouseClicked

    private void CodeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_CodeComponentAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_CodeComponentAdded

    private void subcodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subcodeMouseEntered
        // TODO add your handling code here:
          try{
             //JTextField subcode= 
           
             subcode.setEditable(false);
             String Fetch_row="Select * from subject where sub_code=?";
                PreparedStatement pst=Con.prepareStatement(Fetch_row);
                pst.setString(1,(String)Code.getSelectedItem());
                Rs=pst.executeQuery();
                while(Rs.next())
                {
                        subcode.setText(Rs.getString("sub_code"));
                        subname.setText(Rs.getString("sub_name"));
                        thours.setText(Rs.getString("sub_teachhours"));
                       // coursecb.toString(Rs.getSelectedItem()("sub_code"));
                       coursecb.setSelectedItem(Rs.getString("sub_course").toString());
                       //GenderCb.setSelectedItem(model.getValueAt(Myindex,3).toString());
                        
                }
                
        }catch(Exception e)
        {
        
        }
        
    }//GEN-LAST:event_subcodeMouseEntered

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        // TODO add your handling code here:
        subcode.setText("");
        subname.setText("");
        thours.setText("");
    }//GEN-LAST:event_resetMouseClicked

    private void valNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valNameActionPerformed

    private void subcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subcodeKeyReleased
        // TODO add your handling code here:
        String pattern="^[0-9]{1,20}$";
        Pattern patt=Pattern.compile(pattern);
        Matcher match=patt.matcher(subcode.getText());
        if(!match.matches())
        {
            valCode.setText("Ineger Number Only");
        }
        else
        {
               valCode.setText("");
        }
    }//GEN-LAST:event_subcodeKeyReleased

    private void subnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subnameKeyReleased
        // TODO add your handling code here:
         String pattern="^[a-zA-Z ]{1,30}$";
        Pattern patt=Pattern.compile(pattern);
        Matcher match=patt.matcher(subname.getText());
        if(!match.matches())
        {
            valName.setText("Enter Valid Name");
        }
        else
        {
               valName.setText("");
        }
    }//GEN-LAST:event_subnameKeyReleased

    private void thoursKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thoursKeyReleased
        // TODO add your handling code here:
        String pattern="^[0-9]{1,3}$";
        Pattern patt=Pattern.compile(pattern);
        Matcher match=patt.matcher(thours.getText());
        if(!match.matches())
        {
            valHours.setText("Number Only");
        }
        else
        {
               valHours.setText("");
        }
    }//GEN-LAST:event_thoursKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Code;
    private javax.swing.JComboBox<String> coursecb;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton reset;
    private javax.swing.JTextField subcode;
    private javax.swing.JTextField subname;
    private javax.swing.JTextField thours;
    private javax.swing.JButton update;
    private javax.swing.JTextField valCode;
    private javax.swing.JTextField valHours;
    private javax.swing.JTextField valName;
    // End of variables declaration//GEN-END:variables


    
}




