/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.CardLayout;

/**
 *
 * @author samar
 */
public class student extends javax.swing.JPanel {

    /**
     * Creates new form faculty
     */
    public student() {
        initComponents();
        
        add_student add_stud = new add_student();
        modify_student modify_stud = new modify_student();
        view_student view_stud = new view_student();
        
        student_tab_holder.setLayout(new CardLayout());

        student_tab_holder.add("add student", add_stud);
        student_tab_holder.add("modify student", modify_stud);
        student_tab_holder.add("view student", view_stud);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        label_add_subject = new javax.swing.JLabel();
        label_modify_subject = new javax.swing.JLabel();
        label_view_subject = new javax.swing.JLabel();
        student_tab_holder = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(940, 540));
        setMinimumSize(new java.awt.Dimension(940, 540));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(940, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(170, 450));
        jPanel3.setMinimumSize(new java.awt.Dimension(170, 450));

        jPanel5.setBackground(new java.awt.Color(204, 255, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_add_subject.setBackground(new java.awt.Color(204, 255, 51));
        label_add_subject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_add_subject.setForeground(new java.awt.Color(51, 51, 51));
        label_add_subject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_add_subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/add_32.png"))); // NOI18N
        label_add_subject.setText("ADD STUDENT");
        label_add_subject.setName("label_add_subject"); // NOI18N
        label_add_subject.setOpaque(true);
        label_add_subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_add_subjectMouseClicked(evt);
            }
        });

        label_modify_subject.setBackground(new java.awt.Color(204, 255, 51));
        label_modify_subject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_modify_subject.setForeground(new java.awt.Color(51, 51, 51));
        label_modify_subject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_modify_subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/edit_32.png"))); // NOI18N
        label_modify_subject.setText("MODIFY STUDENT");
        label_modify_subject.setName("label_modify_subject"); // NOI18N
        label_modify_subject.setOpaque(true);
        label_modify_subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_modify_subjectMouseClicked(evt);
            }
        });

        label_view_subject.setBackground(new java.awt.Color(204, 255, 51));
        label_view_subject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_view_subject.setForeground(new java.awt.Color(51, 51, 51));
        label_view_subject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_view_subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/view_32.png"))); // NOI18N
        label_view_subject.setText("VIEW STUDENT");
        label_view_subject.setName("label_view_subject"); // NOI18N
        label_view_subject.setOpaque(true);
        label_view_subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_view_subjectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_add_subject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_modify_subject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(label_view_subject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(label_add_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_modify_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_view_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));
        jPanel3.getAccessibleContext().setAccessibleName("");

        student_tab_holder.setBackground(new java.awt.Color(255, 255, 255));
        student_tab_holder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 51), 2));
        student_tab_holder.setMaximumSize(new java.awt.Dimension(680, 520));
        student_tab_holder.setMinimumSize(new java.awt.Dimension(680, 520));

        javax.swing.GroupLayout student_tab_holderLayout = new javax.swing.GroupLayout(student_tab_holder);
        student_tab_holder.setLayout(student_tab_holderLayout);
        student_tab_holderLayout.setHorizontalGroup(
            student_tab_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        student_tab_holderLayout.setVerticalGroup(
            student_tab_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        add(student_tab_holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 740, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void label_add_subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_add_subjectMouseClicked
        CardLayout cl = (CardLayout) student_tab_holder.getLayout();
        cl.show(student_tab_holder, "add student");
    }//GEN-LAST:event_label_add_subjectMouseClicked

    private void label_modify_subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_modify_subjectMouseClicked
        CardLayout cl = (CardLayout) student_tab_holder.getLayout();
        cl.show(student_tab_holder, "modify student");
    }//GEN-LAST:event_label_modify_subjectMouseClicked

    private void label_view_subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_view_subjectMouseClicked
        CardLayout cl = (CardLayout) student_tab_holder.getLayout();
        cl.show(student_tab_holder, "view student");
    }//GEN-LAST:event_label_view_subjectMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel label_add_subject;
    private javax.swing.JLabel label_modify_subject;
    private javax.swing.JLabel label_view_subject;
    private javax.swing.JPanel student_tab_holder;
    // End of variables declaration//GEN-END:variables
}
