/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author samar
 */
public class view_attendance extends javax.swing.JPanel {

    
    
    Connection Con = null;
    Statement St, St1 = null;
    ResultSet Rs, Rs1=null;
    
    public view_attendance() {
        initComponents();
        
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_view_attendance = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        div = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sub = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        dept = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        d1 = new javax.swing.JComboBox<>();
        d2 = new javax.swing.JComboBox<>();
        d3 = new javax.swing.JComboBox<>();
        fetch_details = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(740, 520));
        setMinimumSize(new java.awt.Dimension(740, 520));
        setPreferredSize(new java.awt.Dimension(740, 520));

        table_view_attendance.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        table_view_attendance.setForeground(new java.awt.Color(51, 51, 51));
        table_view_attendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_view_attendance.setColumnSelectionAllowed(true);
        table_view_attendance.setMinimumSize(new java.awt.Dimension(404, 440));
        table_view_attendance.setPreferredSize(new java.awt.Dimension(404, 440));
        jScrollPane1.setViewportView(table_view_attendance);
        table_view_attendance.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("DATE :");

        div.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        div.setForeground(new java.awt.Color(51, 51, 51));
        div.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        div.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("SUBJECT :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("YEAR :");

        sub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sub.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("DEPARTMENT :");
        jLabel1.setToolTipText("");

        dept.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dept.setForeground(new java.awt.Color(51, 51, 51));
        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Mechanical (ME)", "Information Technology(IT)", "Chemical(CE)" }));
        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });

        year.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        year.setForeground(new java.awt.Color(51, 51, 51));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Year", "Second Year", "Third Year", "Fourth Year" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("DIV :");

        d1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d1.setForeground(new java.awt.Color(51, 51, 51));
        d1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        d2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d2.setForeground(new java.awt.Color(51, 51, 51));
        d2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        d3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d3.setForeground(new java.awt.Color(51, 51, 51));
        d3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        fetch_details.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fetch_details.setForeground(new java.awt.Color(51, 51, 51));
        fetch_details.setText("Fetch Details");
        fetch_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetch_detailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(fetch_details, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fetch_details)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fetch_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetch_detailsActionPerformed
        
        if(sub.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this,"Kindly Select A Subject !");    
            return;
        }
        
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Con = DriverManager.getConnection("jdbc:ucanaccess://attendance_db/face_recog_db.accdb");
            St = Con.createStatement();
            St1 = Con.createStatement();
         
            String _dept = dept.getSelectedItem().toString();
            String _year = year.getSelectedItem().toString();
            String _div = div.getSelectedItem().toString();

            String d = d1.getSelectedItem().toString();
            String m = d2.getSelectedItem().toString();
            String y = d3.getSelectedItem().toString();
            String date = d + "-" + m + "-" + y;
            String sub_name  = sub.getSelectedItem().toString();
            int sub_id = 0; 
            
            Rs = St.executeQuery("Select sub_code from subject where sub_name='"+ sub_name +"'");
            // Rs = St.executeQuery(Query);
             while(Rs.next())
             {
                sub_id = Integer.parseInt(Rs.getString("sub_code"));
             }
             System.err.println("Query1 Execute Successfully :)");

             String query = "select stud_id from attendance_subject where " + 
                            "subject_id ='"   + sub_id  + "' and " +
                            "date_attend ='"  +  date   + "' and " +
                            "department='"    + _dept   + "' and " +
                            "year='"          + _year   + "' and " +
                            "div='"           + _div    + "'";

            Rs = St.executeQuery(query);
            System.err.println("Query1 Execute Successfully :)");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Roll No");
            model.addColumn("Student Name");
            model.addColumn("Status");

             if(Rs.next())
             {
                do
                {
                    String query1 = "select * from student where stud_id='" + Rs.getString("stud_id") + "'";
                    Rs1 = St1.executeQuery(query1);
                    if(Rs1.next())
                    {
                        String[] temp_row = {   Rs1.getString("stud_id"),
                                                Rs1.getString("stud_roll"),
                                                Rs1.getString("stud_name"),
                                                "Present"
                                            };
                        model.addRow(temp_row);
                    }
                }while(Rs.next());
             }
             else
             {
                 JOptionPane.showMessageDialog(this, "No Details Found..! ");
             }
             
             table_view_attendance.setModel(model);
         
         
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_fetch_detailsActionPerformed

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptActionPerformed
        sub.removeAllItems();
        try
        {
         Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Con = DriverManager.getConnection("jdbc:ucanaccess://attendance_db/face_recog_db.accdb");
         St = Con.createStatement();
        // String Query="Select * from subject";
         Rs = St.executeQuery("Select * from subject where sub_course='"+ dept.getSelectedItem().toString()+"'");
        // Rs = St.executeQuery(Query);
         while(Rs.next())
         {
             String Mycat=Rs.getString("sub_name");
            sub.addItem(Mycat);
          
         }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> d1;
    private javax.swing.JComboBox<String> d2;
    private javax.swing.JComboBox<String> d3;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JComboBox<String> div;
    private javax.swing.JButton fetch_details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> sub;
    private javax.swing.JTable table_view_attendance;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables


    
}




