/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author samar
 */
public class view_student extends javax.swing.JPanel {

    /**
     * Creates new form attendance_fill_manually
     */
    public view_student() {
        initComponents();
        //displayStudentRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jCombo_Stud_div = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCombo_Stud_dept = new javax.swing.JComboBox<>();
        jCombo_Stud_year = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Stud_id = new javax.swing.JTextField();
        searchStud = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(740, 520));
        setMinimumSize(new java.awt.Dimension(740, 520));
        setPreferredSize(new java.awt.Dimension(740, 520));

        StudentTable.setAutoCreateRowSorter(true);
        StudentTable.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        StudentTable.setForeground(new java.awt.Color(51, 51, 51));
        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STUD ID", "ROLL NO", "NAME", "Email ID", "Mobile No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentTable.setColumnSelectionAllowed(true);
        StudentTable.setMinimumSize(new java.awt.Dimension(404, 440));
        StudentTable.setPreferredSize(new java.awt.Dimension(404, 440));
        jScrollPane1.setViewportView(StudentTable);
        StudentTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (StudentTable.getColumnModel().getColumnCount() > 0) {
            StudentTable.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCombo_Stud_div.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCombo_Stud_div.setForeground(new java.awt.Color(51, 51, 51));
        jCombo_Stud_div.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jCombo_Stud_div.setToolTipText("");
        jCombo_Stud_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_Stud_divActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("DEPARTMENT :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("YEAR :");

        jCombo_Stud_dept.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCombo_Stud_dept.setForeground(new java.awt.Color(51, 51, 51));
        jCombo_Stud_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Mechanical (ME)", "Information Technology(IT)", "Chemical(CE)" }));
        jCombo_Stud_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_Stud_deptActionPerformed(evt);
            }
        });

        jCombo_Stud_year.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCombo_Stud_year.setForeground(new java.awt.Color(51, 51, 51));
        jCombo_Stud_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Year", "Second Year", "Third Year", "Fourth Year" }));
        jCombo_Stud_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_Stud_yearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("DIV :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jCombo_Stud_year, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(jCombo_Stud_div, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jCombo_Stud_dept, 0, 300, Short.MAX_VALUE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo_Stud_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo_Stud_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo_Stud_div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        Stud_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Stud_id.setForeground(new java.awt.Color(51, 51, 51));
        Stud_id.setToolTipText("Search");
        Stud_id.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        searchStud.setBackground(new java.awt.Color(255, 255, 255));
        searchStud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchStud.setForeground(new java.awt.Color(51, 51, 51));
        searchStud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_search_24px.png"))); // NOI18N
        searchStud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchStudMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Student Id : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(Stud_id, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(searchStud)
                        .addGap(162, 162, 162))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchStud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Stud_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCombo_Stud_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_Stud_deptActionPerformed
        // TODO add your handling code here:
        displayStudentRecords();
    }//GEN-LAST:event_jCombo_Stud_deptActionPerformed

    private void jCombo_Stud_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_Stud_yearActionPerformed
        // TODO add your handling code here:
        displayStudentRecords();
    }//GEN-LAST:event_jCombo_Stud_yearActionPerformed

    private void jCombo_Stud_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_Stud_divActionPerformed
        // TODO add your handling code here:
        displayStudentRecords();
    }//GEN-LAST:event_jCombo_Stud_divActionPerformed

    private void searchStudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStudMouseClicked
        // TODO add your handling code here:
        
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                Connection con = DriverManager.getConnection("jdbc:ucanaccess://attendance_db/face_recog_db.accdb");

            String studId = Stud_id.getText();

            Statement st = con.createStatement();
            String sql = "select stud_roll,stud_name,stud_dept,stud_year,stud_div from student where stud_id="+studId+"";

            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, " Student Record Found.. ");
            } else {
                JOptionPane.showMessageDialog(this, " Sorry..! Record Not Found.. ");
            }

            rs.close();
            st.close();
            con.close();
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchStudMouseClicked
    
    public void displayStudentRecords() {

        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://attendance_db/face_recog_db.accdb");

            String dept = jCombo_Stud_dept.getSelectedItem().toString();
            String year = jCombo_Stud_year.getSelectedItem().toString();
            String div = jCombo_Stud_div.getSelectedItem().toString();
            
            String sql = "SELECT stud_id,stud_roll,stud_name,stud_email,stud_mobile FROM student WHERE stud_dept=? AND stud_year=? AND stud_div=?";
            PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setString(1, dept);
            ps.setString(2, year);
            ps.setString(3, div);
            
            ResultSet rs = ps.executeQuery();
            StudentTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            /*if(!rs.next()) {
                JOptionPane.showMessageDialog(this, " Sorry..! Records Not Found.. ");
            }*/

            rs.close();
            ps.close();
            con.close();
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Stud_id;
    private javax.swing.JTable StudentTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jCombo_Stud_dept;
    private javax.swing.JComboBox<String> jCombo_Stud_div;
    private javax.swing.JComboBox<String> jCombo_Stud_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel searchStud;
    // End of variables declaration//GEN-END:variables

}




